### ISSUE TITLE
How to set height automatically to keep scale ratio with width?

### ISSUE THREAD

**Issue by hsluoyz** [wangsijie/aliplayer-react#3]
The example uses:

```js
const config = {
    source: "//player.alicdn.com/video/aliyunmedia.mp4",
    width: "100%",
    height: "500px",
    autoplay: true,
    isLive: false,
    rePlay: false,
    playsinline: true,
    preload: true,
    controlBarVisibility: "hover",
    useH5Prism: true,
    components: [
        {
            name: "RateComponent",
            type: Player.components.RateComponent,
        }
    ]
};
```

But I want the height to be auto scaled with the width: 100%. I can set height manually but I still need the resolution of the video?

**Comment by wangsijie** [comment]
@hsluoyz You can set width and height to 100%, and wrap the player with a div, then set the div's width to 500px.
```jsx
<div style={{ width: '500px' }}>
  <Aliplayer config={{ width: '100%', height: '100%' }} />
</div>
```

**Comment by hsluoyz** [comment]
It's not working. The video window will overlay on other components. Is there any other way? Like get the video resolution? So I can adjust height by myself.

**Comment by wangsijie** [comment]
After getting player instance (onGetInstance), you can try to get video info via aliplayer's api. https://help.aliyun.com/document_detail/125572.html?spm=a2c4g.11174283.6.1087.4603149bANT89V

**Comment by wangsijie** [comment]
Hi @hsluoyz , I will close this issue for now. If the solution above doesn't work, you can reopen anytime
