### ISSUE TITLE
How to reload the player after updating the config?

### ISSUE THREAD

**Issue by hsluoyz** [wangsijie/aliplayer-react#4]
When we update the config, like the width, height, the player window is not updated automatically. How to reload/refresh/recreate the player component when config is updated?

**Comment by wangsijie** [comment]
You cannot simply reload the player for now, and it's not recommended, reloading will create multiple instance and may cause performance problems.
You can change player config using aliplayer's api, such as `setPlayerSize` https://help.aliyun.com/document_detail/125572.html?spm=a2c4g.11174283.6.1087.4603149bANT89V#h2-u64ADu653Eu5668u63A5u53E32

**Comment by hsluoyz** [comment]
It has a `dispose()` method: https://help.aliyun.com/document_detail/125572.html

Can we use it to implement the `refresh` functionality?

**Comment by wangsijie** [comment]
This may cause interruption on video playing. It's not recommended
