### ISSUE TITLE
  Can this  aliplayer-react component be used on React Native?

### ISSUE THREAD

**Issue by xuezhimin** [wangsijie/aliplayer-react#7]

**Comment by wangsijie** [comment]
The answer is NO.

This is a web-based browser. For native use: https://help.aliyun.com/document_detail/51992.html?spm=a2c4g.11186623.6.1029.1d9a219c4wXes1

**Comment by xuezhimin** [comment]
OK，thank you

**Comment by xuezhimin** [comment]
ok,thank you,I go to try


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangsijie/aliplayer-react"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月28日(星期二) 中午12:39
收件人:&nbsp;"wangsijie/aliplayer-react"<aliplayer-react@noreply.github.com&gt;;
抄送:&nbsp;"褚君"<2771905288@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangsijie/aliplayer-react]   Can this  aliplayer-react component be used on React Native? (#7)





 
Closed #7.
